before_install:
 - cd ${TMPDIR-/tmp}
 - wget -q http://doxygen.nl/files/doxygen-1.8.19.src.tar.gz
 - tar -xzvf doxygen-1.8.19.src.tar.gz
 - mkdir doxygen_build
 - cd doxygen_build
 - cmake ../doxygen-1.8.19/
 - make
 - export PATH="${TMPDIR-/tmp}/doxygen_build/bin:$PATH"
 - cd ${TRAVIS_BUILD_DIR}
 
branches:
  only:
    - master

script:
  - doxygen ./docs/Doxyfile

deploy:
  provider: pages
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master