var searchData=
[
  ['a_20client_0',['Creating a Client',['../md__new__user__guide.html#creating-a-client',1,'']]],
  ['a_20server_1',['Creating a Server',['../md__new__user__guide.html#creating-a-server',1,'']]],
  ['a_20task_20running_20on_20the_20nimble_20stack_20core_2',['Put BLE functions in a task running on the NimBLE stack core',['../md__usage__tips.html#put-ble-functions-in-a-task-running-on-the-nimble-stack-core',1,'']]],
  ['about_20extended_20advertising_3',['About extended advertising',['../md__bluetooth_015_01features.html#about-extended-advertising',1,'']]],
  ['acknowledgments_4',['Acknowledgments',['../index.html#acknowledgments',1,'']]],
  ['adddata_5',['adddata',['../class_nim_b_l_e_advertisement_data.html#a051d8f4ae66d2caa39351af8277bf0ed',1,'NimBLEAdvertisementData::addData(const std::vector&lt; uint8_t &gt; &amp;data)'],['../class_nim_b_l_e_advertisement_data.html#a67f4d6869eb2797bc78389adf20cb59e',1,'NimBLEAdvertisementData::addData(const uint8_t *data, size_t length)']]],
  ['added_6',['added',['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#added-10',1,'Added'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#added-12',1,'Added'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#added-11',1,'Added'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#added-9',1,'Added'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#added-8',1,'Added'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#added-7',1,'Added'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#added-6',1,'Added'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#added-5',1,'Added'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#added-3',1,'Added'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#added-2',1,'Added'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#added-1',1,'Added'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#added',1,'Added'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#added-4',1,'Added']]],
  ['addresses_7',['addresses',['../md_1_8x__to2_8x__migration__guide.html#ble-addresses',1,'BLE Addresses'],['../md__migration__guide.html#ble-addresses-1',1,'BLE Addresses']]],
  ['addserviceuuid_8',['addserviceuuid',['../class_nim_b_l_e_advertisement_data.html#a4119cfc1dafeee9c32f9a08dbb213139',1,'NimBLEAdvertisementData::addServiceUUID()'],['../class_nim_b_l_e_advertising.html#a1bacfa32690f7e0c6f1172ea03c68c0d',1,'NimBLEAdvertising::addServiceUUID()'],['../class_nim_b_l_e_advertisement_data.html#acbea9f95711b329a427919ecd9cbeb23',1,'NimBLEAdvertisementData::addServiceUUID()'],['../class_nim_b_l_e_advertising.html#a67c9589dff7e0ee3ec24f2c930d56c06',1,'NimBLEAdvertising::addServiceUUID(const NimBLEUUID &amp;serviceUUID)']]],
  ['addtxpower_9',['addtxpower',['../class_nim_b_l_e_advertising.html#a0d3c5cb3a93416a4206abb1f8e443ebf',1,'NimBLEAdvertising::addTxPower()'],['../class_nim_b_l_e_advertisement_data.html#a3f227c597ec00f639e4bd26b80ce404b',1,'NimBLEAdvertisementData::addTxPower()']]],
  ['advertised_20device_10',['Advertised Device',['../md_1_8x__to2_8x__migration__guide.html#advertised-device',1,'']]],
  ['advertising_11',['advertising',['../md__bluetooth_015_01features.html#about-extended-advertising',1,'About extended advertising'],['../md_1_8x__to2_8x__migration__guide.html#advertising',1,'Advertising'],['../md__bluetooth_015_01features.html#enabling-extended-advertising',1,'Enabling extended advertising']]],
  ['advertising_20api_12',['Advertising API',['../md__migration__guide.html#advertising-api',1,'']]],
  ['advtypetostring_13',['advTypeToString',['../class_nim_b_l_e_utils.html#a6de9354eeba9f126aa14cfa7ed43cda4',1,'NimBLEUtils']]],
  ['and_20characteristics_20needed_14',['Only retrieve the services and characteristics needed',['../md__usage__tips.html#only-retrieve-the-services-and-characteristics-needed',1,'']]],
  ['api_15',['api',['../md__migration__guide.html#advertising-api',1,'Advertising API'],['../md__migration__guide.html#client-api',1,'Client API'],['../md__migration__guide.html#security-api',1,'Security API'],['../md__migration__guide.html#server-api',1,'Server API']]],
  ['append_16',['append',['../class_nim_b_l_e_att_value.html#aa217dfc649daed50eb75c7168442f86e',1,'NimBLEAttValue']]],
  ['arduino_20configuration_17',['Arduino Configuration',['../md__migration__guide.html#arduino-configuration',1,'']]]
];
