var searchData=
[
  ['features_0',['Bluetooth 5.x features',['../md__bluetooth_015_01features.html',1,'']]],
  ['files_1',['files',['../md__migration__guide.html#header-files',1,'Header Files'],['../md__new__user__guide.html#include-files',1,'Include Files']]],
  ['fixed_2',['fixed',['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-20',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-19',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-18',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-17',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-16',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-15',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-14',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-13',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-12',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-11',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-10',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-9',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-8',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-7',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-6',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-5',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-4',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-3',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-2',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed-1',1,'Fixed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#fixed',1,'Fixed']]],
  ['from_201_20x_20to_202_20x_3',['Migrating from 1.x to 2.x',['../md_1_8x__to2_8x__migration__guide.html',1,'']]],
  ['from_20bluedroid_20to_20nimble_4',['Migrating from Bluedroid to NimBLE',['../md__migration__guide.html',1,'']]],
  ['fromstring_5',['fromString',['../class_nim_b_l_e_u_u_i_d.html#ae09acdc52e23a3a38c57aaf859c278c2',1,'NimBLEUUID']]],
  ['full_20list_20of_20properties_6',['The full list of properties',['../md__migration__guide.html#the-full-list-of-properties',1,'']]],
  ['functions_20in_20a_20task_20running_20on_20the_20nimble_20stack_20core_7',['Put BLE functions in a task running on the NimBLE stack core',['../md__usage__tips.html#put-ble-functions-in-a-task-running-on-the-nimble-stack-core',1,'']]]
];
