var searchData=
[
  ['c_5fstr_0',['c_str',['../class_nim_b_l_e_att_value.html#a4d18b6e6839afc943f11200e76414c17',1,'NimBLEAttValue']]],
  ['callbacks_1',['callbacks',['../md_1_8x__to2_8x__migration__guide.html#characteristic-callbacks',1,'Characteristic callbacks'],['../md__migration__guide.html#characteristic-callbacks-1',1,'Characteristic callbacks'],['../md_1_8x__to2_8x__migration__guide.html#client-callbacks',1,'Client callbacks'],['../md__migration__guide.html#client-callbacks-1',1,'Client callbacks'],['../md__migration__guide.html#descriptor-callbacks',1,'Descriptor callbacks']]],
  ['capacity_2',['capacity',['../class_nim_b_l_e_att_value.html#a49a8a126d0b534c999c4a341cdcf7ba2',1,'NimBLEAttValue']]],
  ['changed_3',['changed',['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-3',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-1',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-15',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-14',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-13',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-12',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-11',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-10',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-9',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-8',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-7',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-6',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-5',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-4',1,'Changed'],['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#changed-2',1,'Changed']]],
  ['changelog_4',['Changelog',['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['changes_5',['General changes',['../md_1_8x__to2_8x__migration__guide.html#general-changes',1,'']]],
  ['changes_20strong_6',['&lt;strong&gt;Breaking changes&lt;/strong&gt;',['../md__2github_2workspace_2_c_h_a_n_g_e_l_o_g.html#breaking-changes',1,'']]],
  ['characteristic_20callbacks_7',['characteristic callbacks',['../md__migration__guide.html#characteristic-callbacks-1',1,'Characteristic callbacks'],['../md_1_8x__to2_8x__migration__guide.html#characteristic-callbacks',1,'Characteristic callbacks']]],
  ['characteristics_8',['characteristics',['../md__migration__guide.html#characteristics-1',1,'Characteristics'],['../md_1_8x__to2_8x__migration__guide.html#characteristics',1,'Characteristics'],['../md_1_8x__to2_8x__migration__guide.html#remote-characteristics',1,'Remote Characteristics'],['../md__migration__guide.html#remote-characteristics-1',1,'Remote Characteristics']]],
  ['characteristics_20needed_9',['Only retrieve the services and characteristics needed',['../md__usage__tips.html#only-retrieve-the-services-and-characteristics-needed',1,'']]],
  ['check_20return_20values_10',['Check return values',['../md__usage__tips.html#check-return-values',1,'']]],
  ['class_20names_11',['Class Names',['../md__migration__guide.html#class-names',1,'']]],
  ['cleardata_12',['cleardata',['../class_nim_b_l_e_advertising.html#af7cee42f24ad38872936a0bbc9e2ac1e',1,'NimBLEAdvertising::clearData()'],['../class_nim_b_l_e_advertisement_data.html#ac0f2238cf17bf3e8bbef8b0ef0d61dcf',1,'NimBLEAdvertisementData::clearData()']]],
  ['client_13',['client',['../md_1_8x__to2_8x__migration__guide.html#client',1,'Client'],['../md__new__user__guide.html#creating-a-client',1,'Creating a Client']]],
  ['client_20api_14',['Client API',['../md__migration__guide.html#client-api',1,'']]],
  ['client_20callbacks_15',['client callbacks',['../md__migration__guide.html#client-callbacks-1',1,'Client callbacks'],['../md_1_8x__to2_8x__migration__guide.html#client-callbacks',1,'Client callbacks']]],
  ['client_20instances_20unless_20necessary_20or_20unused_16',['Do not delete client instances unless necessary or unused',['../md__usage__tips.html#do-not-delete-client-instances-unless-necessary-or-unused',1,'']]],
  ['client_20security_17',['Client Security',['../md__migration__guide.html#client-security',1,'']]],
  ['configuration_18',['Arduino Configuration',['../md__migration__guide.html#arduino-configuration',1,'']]],
  ['core_19',['Put BLE functions in a task running on the NimBLE stack core',['../md__usage__tips.html#put-ble-functions-in-a-task-running-on-the-nimble-stack-core',1,'']]],
  ['creating_20a_20client_20',['Creating a Client',['../md__new__user__guide.html#creating-a-client',1,'']]],
  ['creating_20a_20server_21',['Creating a Server',['../md__new__user__guide.html#creating-a-server',1,'']]]
];
